version: '2'
services:
    employeemanagementservice-app:
        image: employeemanagementservice
        external_links:
            - employeemanagementservice-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/EmployeeManagementService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    employeemanagementservice-postgresql:
        extends:
            file: postgresql.yml
            service: employeemanagementservice-postgresql
